"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UNKNOWN_ACTION = exports.THROW_ERROR = exports.UNSUBSCRIBE_IN_MIDDLE = exports.SUBSCRIBE_IN_MIDDLE = exports.INIT = exports.GET_STATE_IN_MIDDLE = exports.DISPATCH_IN_MIDDLE = exports.ADD_TODO = void 0;
exports.ADD_TODO = 'ADD_TODO';
exports.DISPATCH_IN_MIDDLE = 'DISPATCH_IN_MIDDLE';
exports.GET_STATE_IN_MIDDLE = 'GET_STATE_IN_MIDDLE';
exports.INIT = '@@INIT';
exports.SUBSCRIBE_IN_MIDDLE = 'SUBSCRIBE_IN_MIDDLE';
exports.UNSUBSCRIBE_IN_MIDDLE = 'UNSUBSCRIBE_IN_MIDDLE';
exports.THROW_ERROR = 'THROW_ERROR';
exports.UNKNOWN_ACTION = 'UNKNOWN_ACTION';
